(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require list.List.
Require list.Length.
Require list.Nth.
Require option.Option.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

(* Why3 assumption *)
Fixpoint map {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b} (f:a -> b)
  (l:Init.Datatypes.list a) {struct l}: Init.Datatypes.list b :=
  match l with
  | Init.Datatypes.nil => Init.Datatypes.nil
  | Init.Datatypes.cons x r => Init.Datatypes.cons (f x) (map f r)
  end.

(* Why3 assumption *)
Inductive list (a:Type) :=
  | Nil : list a
  | Cons : a -> list a -> list a.
Axiom list_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (list a).
Existing Instance list_WhyType.
Arguments Nil {a}.
Arguments Cons {a}.

(* Why3 assumption *)
Definition is_nil {a:Type} {a_WT:WhyType a} (l:list a) : Prop :=
  match l with
  | Nil => True
  | Cons _ _ => False
  end.

Axiom is_nil'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (l:list a), is_nil l <-> (l = (Nil : list a)).

(* Why3 assumption *)
Definition hd {a:Type} {a_WT:WhyType a} (l:list a) : Init.Datatypes.option a :=
  match l with
  | Nil => Init.Datatypes.None
  | Cons h _ => Init.Datatypes.Some h
  end.

(* Why3 assumption *)
Definition tl {a:Type} {a_WT:WhyType a} (l:list a) :
    Init.Datatypes.option (list a) :=
  match l with
  | Nil => Init.Datatypes.None
  | Cons _ t => Init.Datatypes.Some t
  end.

(* Why3 assumption *)
Fixpoint at_time {a:Type} {a_WT:WhyType a} (i:Numbers.BinNums.Z) (x:a)
  (l:Init.Datatypes.list a) {struct l}: Prop :=
  match l with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons y r =>
      (i = (list.Length.length r)) /\ (x = y) \/ at_time i x r
  end.

(* Why3 assumption *)
Definition forall_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  forall (i:Numbers.BinNums.Z) (x:a), at_time i x h ->
  ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Definition exists_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  exists i:Numbers.BinNums.Z, exists x:a,
  at_time i x h /\ ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Inductive var_t :=
  | var_t'mk : Numbers.BinNums.Z -> var_t.
Axiom var_t_WhyType : WhyType var_t.
Existing Instance var_t_WhyType.

(* Why3 assumption *)
Definition var_state (v:var_t) : Numbers.BinNums.Z :=
  match v with
  | var_t'mk x => x
  end.

(* Why3 assumption *)
Inductive env_t :=
  | env_t'mk : Numbers.BinNums.Z ->
      Init.Datatypes.option Numbers.BinNums.Z -> env_t.
Axiom env_t_WhyType : WhyType env_t.
Existing Instance env_t_WhyType.

(* Why3 assumption *)
Definition input_on (v:env_t) : Numbers.BinNums.Z :=
  match v with
  | env_t'mk x x1 => x
  end.

(* Why3 assumption *)
Definition output_light (v:env_t) : Init.Datatypes.option Numbers.BinNums.Z :=
  match v with
  | env_t'mk x x1 => x1
  end.

(* Why3 assumption *)
Inductive h_env_t :=
  | h_env_t'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z ->
      Numbers.BinNums.Z -> h_env_t.
Axiom h_env_t_WhyType : WhyType h_env_t.
Existing Instance h_env_t_WhyType.

(* Why3 assumption *)
Definition h_input_on (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 => x
  end.

(* Why3 assumption *)
Definition h_output_light (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 => x1
  end.

(* Why3 assumption *)
Definition h_var_state (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 => x2
  end.

(* Why3 assumption *)
Inductive history_t :=
  | history_t'mk : Init.Datatypes.list h_env_t -> history_t.
Axiom history_t_WhyType : WhyType history_t.
Existing Instance history_t_WhyType.

(* Why3 assumption *)
Definition h_envs (v:history_t) : Init.Datatypes.list h_env_t :=
  match v with
  | history_t'mk x => x
  end.

Parameter fc:
  Numbers.BinNums.Z ->
  Numbers.BinNums.Z ->
  h_env_t -> Init.Datatypes.list h_env_t -> Init.Datatypes.bool.

Parameter fc1:
  Numbers.BinNums.Z ->
  h_env_t -> Init.Datatypes.list h_env_t -> Init.Datatypes.bool.

Axiom fc'def :
  forall (i:Numbers.BinNums.Z) (j:Numbers.BinNums.Z) (h_env_j:h_env_t)
    (h:Init.Datatypes.list h_env_t),
  ((fc i j h_env_j h) = Init.Datatypes.true) <->
  (j <= i)%Z /\ ((h_input_on h_env_j) = 1%Z).

Axiom fc'def1 :
  forall (i:Numbers.BinNums.Z) (h_env_i:h_env_t)
    (h:Init.Datatypes.list h_env_t),
  ((fc1 i h_env_i h) = Init.Datatypes.true) <->
  (((h_output_light h_env_i) = 1%Z) -> exists_i (fc i) h).

(* Why3 assumption *)
Definition inv (h:Init.Datatypes.list h_env_t) : Prop := forall_i fc1 h.

Parameter usvar: Numbers.BinNums.Z.

Axiom H : (usvar = 0%Z).

Axiom Assert : (usvar = 0%Z).

Parameter usvar1: Numbers.BinNums.Z.

Parameter ushistory: Init.Datatypes.list h_env_t.

Axiom LoopInvariant : inv ushistory.

Parameter a: Numbers.BinNums.Z.

Parameter usenv: env_t.

Axiom H1 : ((input_on usenv) = a).

Axiom H2 : ((output_light usenv) = Init.Datatypes.None).

Parameter infix_eq'result'unused: Init.Datatypes.bool.

Axiom infix_eq'result'unused'def :
  (((input_on usenv) = 1%Z) ->
   (infix_eq'result'unused = Init.Datatypes.true)) /\
  (~ ((input_on usenv) = 1%Z) ->
   (infix_eq'result'unused = Init.Datatypes.false)).

Axiom H3 : ~ ((input_on usenv) = 1%Z).

Parameter usenv1: env_t.

Axiom H4 : ((input_on usenv1) = (input_on usenv)).

Axiom H5 : ((output_light usenv1) = (Init.Datatypes.Some usvar1)).

Parameter ushistory1: Init.Datatypes.list h_env_t.

Axiom Ensures :
  ((list.Length.length ushistory1) =
   ((list.Length.length ushistory) + 1%Z)%Z).

Axiom Ensures1 :
  match ushistory1 with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons h_env _ =>
      ((h_input_on h_env) = (input_on usenv1)) /\
      ((Init.Datatypes.Some (h_output_light h_env)) = (output_light usenv1)) /\
      ((h_var_state h_env) = usvar1)
  end.

Axiom Ensures2 :
  match ushistory1 with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons _ l => (l = ushistory)
  end.

(* Why3 goal *)
Theorem main'vc : inv ushistory1.
Proof.


Qed.

