(include_subdirs  qualified)

(ocamllex lexer)

; tokens shared across the parsers

(menhir
 (modules tokens)
 (flags --only-tokens)
 (explain false))

(menhir
 (modules tokens common specification/ltl specification/ppltl loopy/ppltl/spec loopy/loopy)
 (merge_into loopyPltlParser)
 (flags
  --external-tokens Tokens
  --unused-token SYMB_AT --unused-token DOLLAR  --unused-token SHARP
  --unused-token UNDERSCORE  
  --unused-token HAT --unused-token QMARK 
  --unused-token ALL --unused-token ANY --unused-token AT 
  --unused-token PREV --unused-token LAST  --unused-token AS
  --unused-token EXISTS_PREV --unused-token EXISTS_INST
  --unused-token FORALL_PREV --unused-token FORALL_INST
  --unused-token FIRST
  --unused-token START
  --unused-token FUNCTION --unused-token REQUIRES
  --unused-token NODE --unused-token RETURNS --unused-token UID 
  --strict
  ))

(menhir
 (modules tokens common specification/ltl loopy/ltl/spec loopy/loopy)
 (merge_into loopyLtlParser)
 (flags
  --external-tokens Tokens
  --unused-token HAT --unused-token QMARK 
  --unused-token UNDERSCORE  
  --unused-token ALL --unused-token ANY --unused-token AT 
  --unused-token ONCE 
  --unused-token YESTERDAY 
  --unused-token HISTORICALLY 
  --unused-token WEAK_YESTERDAY
  --unused-token WEAK_SINCE
  --unused-token SINCE 
  --unused-token FUNCTION --unused-token REQUIRES
  --unused-token NODE --unused-token RETURNS --unused-token UID 
  --unused-precedence-levels
  --strict
  ))

(menhir
 (modules tokens specification/ltl obby/ltl/spec obby/obby)
 (merge_into obbyLtlParser)
 (flags
  --external-tokens Tokens
  --unused-token HAT --unused-token QMARK 
  --unused-token UNDERSCORE  
  --unused-token ALL --unused-token ANY --unused-token AT 
  --unused-token ONCE 
  --unused-token YESTERDAY 
  --unused-token HISTORICALLY 
  --unused-token WEAK_YESTERDAY
  --unused-token WEAK_SINCE
  --unused-token SINCE 
  --unused-token INPUT --unused-token OUTPUT 
  --unused-token ENSURES --unused-token REQUIRES 
  --unused-token EMIT --unused-token TO
  --unused-precedence-levels
  --strict
  ))

(library
 (name frontParser)
 (public_name hardy.front_parser)
 (libraries str hardyMisc menhirLib)
 (modules_without_implementation types))
