(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require list.List.
Require list.Length.
Require list.Mem.
Require list.Nth.
Require option.Option.
Require list.HdTl.
Require list.NthHdTl.
Require list.Append.
Require list.Reverse.
Require list.RevAppend.
Require list.NumOcc.
Require list.Permut.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Parameter for_all:
  forall {a:Type} {a_WT:WhyType a}, (a -> Init.Datatypes.bool) ->
  Init.Datatypes.list a -> Init.Datatypes.bool.

Axiom for_all'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  match l with
  | Init.Datatypes.nil => ((for_all p l) = Init.Datatypes.true)
  | Init.Datatypes.cons x r =>
      (((p x) = Init.Datatypes.true) -> ((for_all p l) = (for_all p r))) /\
      (~ ((p x) = Init.Datatypes.true) ->
       ((for_all p l) = Init.Datatypes.false))
  end.

Axiom for_all'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  ((for_all p l) = Init.Datatypes.true) <->
  (forall (x:a), list.Mem.mem x l -> ((p x) = Init.Datatypes.true)).

Parameter for_some:
  forall {a:Type} {a_WT:WhyType a}, (a -> Init.Datatypes.bool) ->
  Init.Datatypes.list a -> Init.Datatypes.bool.

Axiom for_some'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  match l with
  | Init.Datatypes.nil => ((for_some p l) = Init.Datatypes.false)
  | Init.Datatypes.cons x r =>
      (((p x) = Init.Datatypes.true) ->
       ((for_some p l) = Init.Datatypes.true)) /\
      (~ ((p x) = Init.Datatypes.true) -> ((for_some p l) = (for_some p r)))
  end.

Axiom for_some'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  ((for_some p l) = Init.Datatypes.true) <->
  (exists x:a, list.Mem.mem x l /\ ((p x) = Init.Datatypes.true)).

(* Why3 assumption *)
Definition mem {a:Type} {a_WT:WhyType a} (eq:a -> a -> Init.Datatypes.bool)
    (x:a) (l:Init.Datatypes.list a) : Init.Datatypes.bool :=
  for_some (eq x) l.

Axiom mem'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (eq:a -> a -> Init.Datatypes.bool) (x:a) (l:Init.Datatypes.list a),
  ((mem eq x l) = Init.Datatypes.true) <->
  (exists y:a, list.Mem.mem y l /\ ((eq x y) = Init.Datatypes.true)).

(* Why3 assumption *)
Fixpoint fold_left {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
  (f:b -> a -> b) (acc:b) (l:Init.Datatypes.list a) {struct l}: b :=
  match l with
  | Init.Datatypes.nil => acc
  | Init.Datatypes.cons x r => fold_left f (f acc x) r
  end.

Axiom fold_left_append :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (l1:Init.Datatypes.list a) (l2:Init.Datatypes.list a)
    (f:b -> a -> b) (acc:b),
  ((fold_left f acc (Init.Datatypes.app l1 l2)) =
   (fold_left f (fold_left f acc l1) l2)).

(* Why3 assumption *)
Definition input := Numbers.BinNums.Z.

(* Why3 assumption *)
Definition output := Numbers.BinNums.Z.

(* Why3 assumption *)
Definition state := Numbers.BinNums.Z.

(* Why3 assumption *)
Definition history := Init.Datatypes.list Numbers.BinNums.Z.

(* Why3 assumption *)
Definition state_coherent (s:Numbers.BinNums.Z)
    (h:Init.Datatypes.list Numbers.BinNums.Z) : Prop :=
  (s =
   (fold_left
    (fun (y0:Numbers.BinNums.Z) (y1:Numbers.BinNums.Z) => (y0 + y1)%Z) 0%Z h)).

(* Why3 assumption *)
Definition spec (i:Numbers.BinNums.Z) (o:Numbers.BinNums.Z)
    (h:Init.Datatypes.list Numbers.BinNums.Z) : Prop :=
  (o =
   (fold_left
    (fun (y0:Numbers.BinNums.Z) (y1:Numbers.BinNums.Z) => (y0 + y1)%Z) 0%Z
    (Init.Datatypes.cons i h))).

(* Why3 goal *)
Theorem sum'vc :
  forall (h:Init.Datatypes.list Numbers.BinNums.Z) (state1:Numbers.BinNums.Z),
  forall (i:Numbers.BinNums.Z), state_coherent state1 h ->
  forall (state2:Numbers.BinNums.Z), (state2 = (state1 + i)%Z) ->
  spec i state2 h.
(* Why3 intros h state1 i h1 state2 h2. *)
Proof.
intros h state1 i h1 state2 h2.
rewrite h2. induction h.
- unfold state_coherent in h1. simpl in h1.
  subst. unfold spec. auto.
- unfold spec.
Qed.

