(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require list.List.
Require list.Length.
Require list.Mem.
Require list.Nth.
Require option.Option.
Require list.HdTl.
Require list.NthHdTl.
Require list.Append.
Require list.Reverse.
Require list.RevAppend.
Require list.NumOcc.
Require list.Permut.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Parameter for_all:
  forall {a:Type} {a_WT:WhyType a}, (a -> Init.Datatypes.bool) ->
  Init.Datatypes.list a -> Init.Datatypes.bool.

Axiom for_all'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  match l with
  | Init.Datatypes.nil => ((for_all p l) = Init.Datatypes.true)
  | Init.Datatypes.cons x r =>
      (((p x) = Init.Datatypes.true) -> ((for_all p l) = (for_all p r))) /\
      (~ ((p x) = Init.Datatypes.true) ->
       ((for_all p l) = Init.Datatypes.false))
  end.

Axiom for_all'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  ((for_all p l) = Init.Datatypes.true) <->
  (forall (x:a), list.Mem.mem x l -> ((p x) = Init.Datatypes.true)).

Parameter for_some:
  forall {a:Type} {a_WT:WhyType a}, (a -> Init.Datatypes.bool) ->
  Init.Datatypes.list a -> Init.Datatypes.bool.

Axiom for_some'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  match l with
  | Init.Datatypes.nil => ((for_some p l) = Init.Datatypes.false)
  | Init.Datatypes.cons x r =>
      (((p x) = Init.Datatypes.true) ->
       ((for_some p l) = Init.Datatypes.true)) /\
      (~ ((p x) = Init.Datatypes.true) -> ((for_some p l) = (for_some p r)))
  end.

Axiom for_some'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> Init.Datatypes.bool) (l:Init.Datatypes.list a),
  ((for_some p l) = Init.Datatypes.true) <->
  (exists x:a, list.Mem.mem x l /\ ((p x) = Init.Datatypes.true)).

(* Why3 assumption *)
Definition mem {a:Type} {a_WT:WhyType a} (eq:a -> a -> Init.Datatypes.bool)
    (x:a) (l:Init.Datatypes.list a) : Init.Datatypes.bool :=
  for_some (eq x) l.

Axiom mem'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (eq:a -> a -> Init.Datatypes.bool) (x:a) (l:Init.Datatypes.list a),
  ((mem eq x l) = Init.Datatypes.true) <->
  (exists y:a, list.Mem.mem y l /\ ((eq x y) = Init.Datatypes.true)).

(* Why3 assumption *)
Fixpoint fold_right {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
  (f:a -> b -> b) (l:Init.Datatypes.list a) (acc:b) {struct l}: b :=
  match l with
  | Init.Datatypes.nil => acc
  | Init.Datatypes.cons x r => f x (fold_right f r acc)
  end.

Axiom fold_right_append :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (l1:Init.Datatypes.list a) (l2:Init.Datatypes.list a)
    (f:a -> b -> b) (acc:b),
  ((fold_right f (Init.Datatypes.app l1 l2) acc) =
   (fold_right f l1 (fold_right f l2 acc))).

(* Why3 assumption *)
Definition input := Numbers.BinNums.Z.

(* Why3 assumption *)
Definition output := Numbers.BinNums.Z.

(* Why3 assumption *)
Inductive state :=
  | state'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
      Numbers.BinNums.Z -> state.
Axiom state_WhyType : WhyType state.
Existing Instance state_WhyType.

(* Why3 assumption *)
Definition first (v:state) : Numbers.BinNums.Z :=
  match v with
  | state'mk x x1 x2 x3 => x
  end.

(* Why3 assumption *)
Definition second (v:state) : Numbers.BinNums.Z :=
  match v with
  | state'mk x x1 x2 x3 => x1
  end.

(* Why3 assumption *)
Definition third (v:state) : Numbers.BinNums.Z :=
  match v with
  | state'mk x x1 x2 x3 => x2
  end.

(* Why3 assumption *)
Definition current (v:state) : Numbers.BinNums.Z :=
  match v with
  | state'mk x x1 x2 x3 => x3
  end.

(* Why3 assumption *)
Definition history := Init.Datatypes.list Numbers.BinNums.Z.

(* Why3 assumption *)
Definition history_coherent (h:Init.Datatypes.list Numbers.BinNums.Z) : Prop :=
  (3%Z <= (list.Length.length h))%Z.

(* Why3 assumption *)
Definition state_coherent (s:state)
    (h:Init.Datatypes.list Numbers.BinNums.Z) : Prop :=
  (((current s) = 2%Z) ->
   ((Init.Datatypes.Some (first s)) = (list.Nth.nth 0%Z h)) /\
   ((Init.Datatypes.Some (second s)) = (list.Nth.nth 1%Z h)) /\
   ((Init.Datatypes.Some (third s)) = (list.Nth.nth 2%Z h))) /\
  (((current s) = 1%Z) ->
   ((Init.Datatypes.Some (first s)) = (list.Nth.nth 1%Z h)) /\
   ((Init.Datatypes.Some (second s)) = (list.Nth.nth 2%Z h)) /\
   ((Init.Datatypes.Some (third s)) = (list.Nth.nth 0%Z h))) /\
  (((current s) = 0%Z) ->
   ((Init.Datatypes.Some (first s)) = (list.Nth.nth 2%Z h)) /\
   ((Init.Datatypes.Some (second s)) = (list.Nth.nth 0%Z h)) /\
   ((Init.Datatypes.Some (third s)) = (list.Nth.nth 1%Z h))) /\
  (0%Z <= (current s))%Z /\ ((current s) < 3%Z)%Z.

(* Why3 assumption *)
Definition spec (i:Numbers.BinNums.Z) (o:Numbers.BinNums.Z)
    (h:Init.Datatypes.list Numbers.BinNums.Z) : Prop :=
  ((list.Nth.nth 2%Z h) = (Init.Datatypes.Some o)).

Parameter h: Init.Datatypes.list Numbers.BinNums.Z.

Parameter s: state.

Parameter i: Numbers.BinNums.Z.

Axiom H : ((current s) = 2%Z).

Parameter s1: state.

Axiom H1 : ((first s1) = i).

Axiom H2 : ((second s1) = (second s)).

Axiom H3 : ((third s1) = (third s)).

Axiom H4 : ((current s1) = (current s)).

Parameter s2: state.

Axiom H5 : ((first s2) = (first s1)).

Axiom H6 : ((second s2) = (second s1)).

Axiom H7 : ((third s2) = (third s1)).

Axiom H8 :
  ((current s2) = (int.EuclideanDivision.mod1 ((current s1) + 1%Z)%Z 3%Z)).

(* Why3 goal *)
Theorem delay3'vc : state_coherent s2 (Init.Datatypes.cons i h).
Proof.


Qed.

