(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require list.List.
Require list.Length.
Require option.Option.

(* Why3 assumption *)
Fixpoint at_time {a:Type} {a_WT:WhyType a} (i:Numbers.BinNums.Z) (x:a)
  (l:Init.Datatypes.list a) {struct l}: Prop :=
  match l with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons y r =>
      (i = (list.Length.length r)) /\ (x = y) \/ at_time i x r
  end.

(* Why3 assumption *)
Definition forall_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  forall (i:Numbers.BinNums.Z) (x:a), at_time i x h ->
  ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Definition exists_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  exists i:Numbers.BinNums.Z, exists x:a,
  at_time i x h /\ ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Definition imm {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) (i:Numbers.BinNums.Z) : Prop :=
  exists x:a, at_time i x h /\ ((p i x h) = Init.Datatypes.true).

Axiom at_time_hd :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:a) (l:Init.Datatypes.list a),
  at_time (list.Length.length l) a1 (Init.Datatypes.cons a1 l).

Axiom at_time_tl :
  forall {a:Type} {a_WT:WhyType a},
  forall (i:Numbers.BinNums.Z) (a1:a) (l:Init.Datatypes.list a),
  (i < (list.Length.length l))%Z -> forall (b:a),
  at_time i a1 (Init.Datatypes.cons b l) -> at_time i a1 l.

Axiom at_time_tl_inv :
  forall {a:Type} {a_WT:WhyType a},
  forall (i:Numbers.BinNums.Z) (a1:a) (l:Init.Datatypes.list a),
  at_time i a1 l -> forall (b:a), at_time i a1 (Init.Datatypes.cons b l).

Axiom at_time_range'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (l:Init.Datatypes.list a), forall (i:Numbers.BinNums.Z) (a1:a),
  at_time i a1 l -> (0%Z <= i)%Z /\ (i < (list.Length.length l))%Z.

Axiom at_time_range_inv'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (l:Init.Datatypes.list a), forall (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < (list.Length.length l))%Z ->
  exists a1:a, at_time i a1 l.

(* Why3 assumption *)
Inductive var_t :=
  | var_t'mk : Numbers.BinNums.Z -> var_t.
Axiom var_t_WhyType : WhyType var_t.
Existing Instance var_t_WhyType.

(* Why3 assumption *)
Definition var_state (v:var_t) : Numbers.BinNums.Z :=
  match v with
  | var_t'mk x => x
  end.

(* Why3 assumption *)
Inductive env_t :=
  | env_t'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z ->
      Init.Datatypes.option Numbers.BinNums.Z -> env_t.
Axiom env_t_WhyType : WhyType env_t.
Existing Instance env_t_WhyType.

(* Why3 assumption *)
Definition input_val (v:env_t) : Numbers.BinNums.Z :=
  match v with
  | env_t'mk x x1 x2 => x
  end.

(* Why3 assumption *)
Definition input_set (v:env_t) : Numbers.BinNums.Z :=
  match v with
  | env_t'mk x x1 x2 => x1
  end.

(* Why3 assumption *)
Definition output_val (v:env_t) : Init.Datatypes.option Numbers.BinNums.Z :=
  match v with
  | env_t'mk x x1 x2 => x2
  end.

(* Why3 assumption *)
Inductive h_env_t :=
  | h_env_t'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z ->
      Numbers.BinNums.Z -> Numbers.BinNums.Z -> h_env_t.
Axiom h_env_t_WhyType : WhyType h_env_t.
Existing Instance h_env_t_WhyType.

(* Why3 assumption *)
Definition h_var_state (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 x3 => x
  end.

(* Why3 assumption *)
Definition h_input_val (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 x3 => x1
  end.

(* Why3 assumption *)
Definition h_input_set (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 x3 => x2
  end.

(* Why3 assumption *)
Definition h_output_val (v:h_env_t) : Numbers.BinNums.Z :=
  match v with
  | h_env_t'mk x x1 x2 x3 => x3
  end.

(* Why3 assumption *)
Inductive history_t :=
  | history_t'mk : Init.Datatypes.list h_env_t -> history_t.
Axiom history_t_WhyType : WhyType history_t.
Existing Instance history_t_WhyType.

(* Why3 assumption *)
Definition h_envs (v:history_t) : Init.Datatypes.list h_env_t :=
  match v with
  | history_t'mk x => x
  end.

Parameter fc:
  Numbers.BinNums.Z ->
  h_env_t -> Init.Datatypes.list h_env_t -> Init.Datatypes.bool.

Axiom fc'def :
  forall (i:Numbers.BinNums.Z) (io:h_env_t) (h:Init.Datatypes.list h_env_t),
  ((fc i io h) = Init.Datatypes.true) <->
  ((0%Z < i)%Z /\ ((h_input_set io) <= 0%Z)%Z ->
   match h with
   | Init.Datatypes.nil => False
   | Init.Datatypes.cons v _ => ((h_output_val io) = (h_output_val v))
   end).

(* Why3 assumption *)
Definition inv_1 (h:Init.Datatypes.list h_env_t) : Prop := forall_i fc h.

Parameter fc1:
  Numbers.BinNums.Z ->
  h_env_t -> Init.Datatypes.list h_env_t -> Init.Datatypes.bool.

Axiom fc'def1 :
  forall (i:Numbers.BinNums.Z) (io:h_env_t) (h:Init.Datatypes.list h_env_t),
  ((fc1 i io h) = Init.Datatypes.true) <->
  ((0%Z < (h_input_set io))%Z -> ((h_output_val io) = (h_input_val io))).

(* Why3 assumption *)
Definition inv_2 (h:Init.Datatypes.list h_env_t) : Prop := forall_i fc1 h.

Parameter usvar: Numbers.BinNums.Z.

Parameter ushistory: Init.Datatypes.list h_env_t.

Axiom LoopInvariant : inv_1 ushistory.

Axiom LoopInvariant1 : inv_2 ushistory.

Parameter usenv: env_t.

Axiom Ensures : ((output_val usenv) = Init.Datatypes.None).

Axiom H : (0%Z < (input_set usenv))%Z.

Parameter usvar1: Numbers.BinNums.Z.

Axiom H1 : (usvar1 = (input_val usenv)).

Axiom Assert : ((output_val usenv) = Init.Datatypes.None).

Parameter usenv1: env_t.

Axiom H2 : ((input_val usenv1) = (input_val usenv)).

Axiom H3 : ((input_set usenv1) = (input_set usenv)).

Axiom H4 : ((output_val usenv1) = (Init.Datatypes.Some usvar1)).

Parameter ushistory1: Init.Datatypes.list h_env_t.

Axiom Ensures1 :
  ((list.Length.length ushistory1) =
   ((list.Length.length ushistory) + 1%Z)%Z).

Axiom Ensures2 :
  match ushistory1 with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons x x1 =>
      ((h_input_val x) = (input_val usenv1)) /\
      ((h_input_set x) = (input_set usenv1)) /\
      ((Init.Datatypes.Some (h_output_val x)) = (output_val usenv1)) /\
      ((h_var_state x) = usvar1)
  end.

Axiom Ensures3 :
  match ushistory1 with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons x x1 => (x1 = ushistory)
  end.

(* Why3 goal *)
Theorem main'vc : inv_1 ushistory1.
Proof.


Qed.

