(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require list.List.
Require list.Length.

(* Why3 assumption *)
Fixpoint at_time {a:Type} {a_WT:WhyType a} (i:Numbers.BinNums.Z) (x:a)
  (l:Init.Datatypes.list a) {struct l}: Prop :=
  match l with
  | Init.Datatypes.nil => False
  | Init.Datatypes.cons y r =>
      (i = (list.Length.length r)) /\ (x = y) \/ at_time i x r
  end.

(* Why3 assumption *)
Definition forall_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  forall (i:Numbers.BinNums.Z) (x:a), at_time i x h ->
  ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Definition exists_i {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) : Prop :=
  exists i:Numbers.BinNums.Z, exists x:a,
  at_time i x h /\ ((p i x h) = Init.Datatypes.true).

(* Why3 assumption *)
Definition imm {a:Type} {a_WT:WhyType a}
    (p:
     Numbers.BinNums.Z -> a -> Init.Datatypes.list a -> Init.Datatypes.bool)
    (h:Init.Datatypes.list a) (i:Numbers.BinNums.Z) : Prop :=
  exists x:a, at_time i x h /\ ((p i x h) = Init.Datatypes.true).

Axiom at_time_hd :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:a) (l:Init.Datatypes.list a),
  at_time (list.Length.length l) a1 (Init.Datatypes.cons a1 l).

Axiom at_time_tl :
  forall {a:Type} {a_WT:WhyType a},
  forall (i:Numbers.BinNums.Z) (a1:a) (l:Init.Datatypes.list a),
  (i < (list.Length.length l))%Z ->
  at_time i a1 (Init.Datatypes.cons a1 l) -> at_time i a1 l.

Axiom at_time_tl_inv :
  forall {a:Type} {a_WT:WhyType a},
  forall (i:Numbers.BinNums.Z) (a1:a) (l:Init.Datatypes.list a),
  at_time i a1 l -> at_time i a1 (Init.Datatypes.cons a1 l).

(* Why3 goal *)
Theorem at_time_range {a:Type} {a_WT:WhyType a} :
  forall (i:Numbers.BinNums.Z) (a1:a) (l:Init.Datatypes.list a),
  at_time i a1 l -> (0%Z <= i)%Z /\ (i < (list.Length.length l))%Z.
Proof.
intros i a1 l h1.

Qed.

